apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        
kind: Deployment
metadata:
  name: eks-jenkins-demo
  labels:
    app: eks-jenkins-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-jenkins-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eks-jenkins-demo
    spec:
      containers:
        - image: chanithadocker/eks-jenkins-demo
          imagePullPolicy: Always
          name: eks-jenkins-demo
          ports:
            - containerPort: 8080
              protocol: TCP